apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sensors.fullname" . }}-controller
  labels:
    {{- include "sensors.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sensors.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sensors.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sensors.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: controller
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: modules
              mountPath: "/sensors"
            - name: ide-storage
              mountPath: "/circuit"
          env:
            - name: APP_NAME
              value: {{ .Release.Name }}
            - name: APP_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: APP_GROUP
              value: {{ .Values.group }}
            - name: APP_VERSION
              value: {{ .Values.version }}
          envFrom:
            - secretRef:
                name: {{ include "sensors.fullname" . }}-rabbitmq
                optional: false
      volumes:
      - name: modules
        configMap:
          name: {{ include "sensors.fullname" . }}
          items:
          - key: modules
            path: modules.yaml
      - name: ide-storage
        persistentVolumeClaim:
          claimName: {{ include "sensors.fullname" . }}-ide-storage
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- range $index, $module := .Values.sensors.modules }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sensors.fullname" $ }}-{{ $module.name }}
  labels:
    {{- include "sensors.labels" $ | nindent 4 }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sensors.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sensors.labels" $ | nindent 8 }}
        {{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sensors.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $module.name }}
          securityContext:
            privileged: true
          image: "{{ $module.image.repository }}:{{ $module.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $module.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $.Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            - name: module
              mountPath: "/sensors"
          envFrom:
            - secretRef:
                name: {{ include "sensors.fullname" $ }}-rabbitmq
                optional: false
      volumes:
      - name: module
        configMap:
          name: {{ include "sensors.fullname" $ }}
          items:
          - key: {{ $module.name }}
            path: module.yaml
      nodeName: {{ $module.nodeName }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sensors.fullname" . }}-ide
  labels:
    {{- include "sensors.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sensors.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sensors.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sensors.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ide
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ide.image.repository }}:{{ .Values.ide.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ide.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ide.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: modules
              mountPath: "/circuit/modules.yaml"
              subPath: "modules.yaml"
            - name: ide-storage
              mountPath: "/circuit"
      initContainers:
        - name: go-scaffold
          image: busybox:1.28
          command: ['sh', '-c', "tar -xvzf /sensors/ide/go-scaffold -C /circuit"]
          volumeMounts:
            - name: ide-storage
              mountPath: "/circuit"
            - name: go-scaffold
              mountPath: "/sensors/ide"
      volumes:
      - name: modules
        configMap:
          name: {{ include "sensors.fullname" . }}
          items:
          - key: modules
            path: modules.yaml
      - name: ide-storage
        persistentVolumeClaim:
          claimName: {{ include "sensors.fullname" . }}-ide-storage
      - name: go-scaffold
        configMap:
          name: {{ include "sensors.fullname" . }}-ide
          items:
          - key: go-scaffold
            path: go-scaffold
      {{- with .Values.ide.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}