apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sensors.fullname" . }}-ide-storage
  labels:
    {{- include "sensors.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ideStorage.storage }}