apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensors.fullname" . }}
  labels:
    {{- include "sensors.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sensors.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensors.fullname" . }}-ide
  labels:
    {{- include "sensors.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ide.service.type }}
  ports:
    - port: {{ .Values.ide.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sensors.selectorLabels" . | nindent 4 }}