apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: circuits.sensors.io
spec:
  group: sensors.io
  scope: Namespaced
  names:
    plural: circuits
    singular: circuit
    kind: Circuit
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              actions:
                description: The chain of actions that Circuit should perform. Actions are performed following the order of elements in actions array
                items:
                  type: object
                  properties:
                    module:
                      description: The module where device is hosted, can be empty
                      type: string
                    device:
                      description: The input device. For index > 0 it will takes the input from previous element's output in the actions array. 
                      type: string
                    op:
                      type: string
                    args:
                      type: object
                      properties:
                        key:
                          type: string
                        value:
                          type: string
                    output:
                      type: object
                      properties:
                        key:
                          type: string
                        value:
                          type: string
                type: array
              frequency:
                type: object
                properties:
                  value:
                    type: string
                  unit:
                    type: string
    selectableFields:
    - jsonPath: .spec.frequency.value
    additionalPrinterColumns:
    - jsonPath: .spec.frequency
      name: Frequency
      type: string