apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: circuits.sensors.io
spec:
  group: sensors.io
  scope: Namespaced
  names:
    plural: circuits
    singular: circuit
    kind: Circuit
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
              module:
                type: string
              device:
                type: string
              actions:
                items:
                  type: object
                  properties:
                    op:
                      type: string
                    frequency:
                      type: object
                      properties:
                        value:
                          type: string
                        unit:
                          type: string
                type: array
    selectableFields:
    - jsonPath: .spec.module
    - jsonPath: .spec.device
    additionalPrinterColumns:
    - jsonPath: .spec.module
      name: Module
      type: string
    - jsonPath: .spec.device
      name: Device
      type: string
