sensors:
  rabbitmq:
    username: admin
    password: password
  modules:
    - name: raspberrypi-0
      type: "Raspberry Pi 3B"
      nodeName: raspberrypi
      image:
        repository: ghcr.io/torchiaf/sensors/module/raspberrypi3b
        pullPolicy: Always
        tag: "main"
      routingKey: raspberrypi-0
      devices:
        - name: dht11
          type: DHT11
          config:
            - name: DHT11_PIN
              value: "12"
            - name: RASPBERRYPI_VERSION
              value: "3"
    - name: raspberrypi-1
      type: "Raspberry Pi 5"
      nodeName: raspberrypi-1
      image:
        repository: ghcr.io/torchiaf/sensors/module/raspberrypi5
        pullPolicy: Always
        tag: "main"
      routingKey: raspberrypi-1
      devices:
        - name: dht11
          type: DHT11
          config:
            - name: DHT11_PIN
              value: "D12"
            - name: RASPBERRYPI_VERSION
              value: "5"
        - name: tm1637
          type: TM1637
          config:
            - name: TM1637_CLK
              value: "27"
            - name: TM1637_DIO
              value: "17"
  devices:
    - name: dht11
      type: DHT11
    - name: tm1637
      type: TM1637
